approvedGitRepositories:
  - "https://github.com/openimis/*.git"
  - "https://github.com/openimis/*"
  - "*"

enableHardenedMode: false

enableScripts: true

enableStrictSsl: false

httpTimeout: 120000

nodeLinker: node-modules
